name: "03-00-Report"

on:
  workflow_dispatch:

jobs:
  test:
    name: "Build and Test"
    runs-on: "ubuntu-latest"
    timeout-minutes: 60
    permissions:
      security-events: read
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: true

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Generate a report"
        uses: ./
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          sarifReportDir: ./samples/sarif/peter-murray/advanced-security-java
          outputDir: ./output
          outputFilename: "summary.pdf"
          templateModelReport: "summary.html"
          repository: ${{ github.workspace }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./output/*.pdf
          retention-days: 3
